-- SELECT p.product_id, COALESCE(ROUND(SUM(p.price::decimal *u.units)/SUM(u.units), 2), 0) as "average_price"
-- FROM Prices p
-- LEFT JOIN UnitsSold u on p.product_id = u.product_id
-- AND u.purchase_date BETWEEN p.start_date AND p.end_date
-- GROUP BY p.product_id